version: '3.8'

volumes:
  couchdb:
  postgresql:

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql-server
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgresql:/var/lib/postgresql/data
    
  couchserver:
    image: couchdb
    container_name: couch-server
    hostname: couchdb-docker.local
    ports:
      - "5984:5984"
    env_file:
      - .env
    volumes:
      - couchdb:/opt/couchdb/data
