--
-- Create Product tables
--
CREATE TABLE IF NOT EXISTS coop_products  (
    "pkey" SERIAL PRIMARY KEY,
    "scrapped_date" date,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "id" VARCHAR(255) NOT NULL,
    "type" VARCHAR(255),
    "ean" VARCHAR(255),
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "manufacturerName" VARCHAR(255),
    "imageUrl" VARCHAR(255),
    "packageSize" REAL,
    "packageSizeInformation" TEXT,
    "packageSizeUnit" VARCHAR(255),
    "salesPrice" REAL,
    "salesPriceData_b2cPrice" REAL,
    "salesPriceData_b2bPrice" REAL,
    "piecePrice" REAL,
    "piecePriceData_b2bPrice" REAL,
    "piecePriceData_b2cPrice" REAL,
    "salesUnit" VARCHAR(255),
    "comparativePriceText" VARCHAR(255),
    "comparativePrice" REAL,
    "comparativePriceData_b2cPrice" REAL,
    "comparativePriceData_b2bPrice" REAL,
    "articleSold" BOOLEAN,
    "deposit" REAL,
    "depositData_b2cPrice" REAL,
    "depositData_b2bPrice" REAL,
    "vat_code" VARCHAR(255),
    "vat_type" VARCHAR(255),
    "vat_value" REAL,
    "animalFoodData" JSON,
    "fromSweden" BOOLEAN,
    "availableOnline" BOOLEAN,
    "nutrientBasis" JSON,
    "onlinePromotions" JSON
);