CREATE TABLE IF NOT EXISTS coop_stores (
	"id" serial PRIMARY KEY,
	"scrapped_date" date,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"storeId" integer,
	"ledgerAccountNumber" text,
	"name" text,
	"address" text,
	"phone" text,
	"openingHoursToday" text,
	"latitude" real,
	"longitude" real,
	"url" text,
	"city" text,
	"postalCode" text
);

-- Create Hemkop stores table
CREATE TABLE IF NOT EXISTS hemkop_stores (
    "id" SERIAL PRIMARY KEY,
    "scrapped_date" DATE,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "externalPickupLocation" BOOLEAN,
    "deliveryCost" TEXT,
    "storeChangeAllowed" BOOLEAN,
    "openingHours" TEXT[],
    "storeId" TEXT,
    "willysHemma" BOOLEAN,
    "clickAndCollect" BOOLEAN,
    "extraPickUpInformation" TEXT,
    "pickingCostForCollect" TEXT,
    "b2bPickingCostForDelivery" TEXT,
    "pickingCostForDelivery" TEXT,
    "b2bDeliveryCost" TEXT,
    "customerServicePhone" TEXT,
    "openingHoursMessageKey" TEXT,
    "onlineStore" BOOLEAN,
    "pickingCostForCollectPlusPickupCost" TEXT,
    "b2bPickingCostForCollectPlusPickupCost" TEXT,
    "pickingCostForDeliveryPlusDeliveryCost" TEXT,
    "b2bPickingCostForDeliveryPlusDeliveryCost" TEXT,
    "openingStoreMessageValue" TEXT,
    "b2BClickAndCollect" BOOLEAN,
    "franchiseStore" BOOLEAN,
    "freeDeliveryThresholdFormatted" TEXT,
    "b2bFreeDeliveryThresholdFormatted" TEXT,
    "pickupInStoreCost" TEXT,
    "b2bPickupInStoreCost" TEXT,
    "customerServiceEmail" TEXT,
    "flyerURL" TEXT,
    "activelySelected" BOOLEAN,
    "freePickingCostThresholdForCollectFormatted" TEXT,
    "freePickingCostThresholdForDeliveryFormatted" TEXT,
    "freeB2BPickingCostThresholdForCollectFormatted" TEXT,
    "freeB2BPickingCostThresholdForDeliveryFormatted" TEXT,
    "external" BOOLEAN,
    "name" TEXT,
    "open" BOOLEAN,
    "specialOpeningHours" TEXT,
    "geoPoint_latitude" REAL,
    "geoPoint_longitude" REAL,
    "address_id" TEXT,
    "address_line1" TEXT,
    "address_town" TEXT,
    "address_postalCode" TEXT,
    "address_country_isocode" TEXT,
    "address_country_name" TEXT,
    "address_shippingAddress" BOOLEAN,
    "address_billingAddress" BOOLEAN,
    "address_defaultAddress" BOOLEAN,
    "address_visibleInAddressBook" BOOLEAN,
    "address_formattedAddress" TEXT,
    "address_longitude" REAL,
    "address_latitude" REAL,
    "address_phone" TEXT,
    "address_email" TEXT
);

-- Create Willys stores table
CREATE TABLE IF NOT EXISTS willys_stores (
    "id" SERIAL PRIMARY KEY,
    "scrapped_date" DATE,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "externalPickupLocation" BOOLEAN,
    "deliveryCost" TEXT,
    "storeChangeAllowed" BOOLEAN,
    "openingHours" TEXT[],
    "storeId" TEXT,
    "willysHemma" BOOLEAN,
    "clickAndCollect" BOOLEAN,
    "extraPickUpInformation" TEXT,
    "pickingCostForCollect" TEXT,
    "b2bPickingCostForDelivery" TEXT,
    "pickingCostForDelivery" TEXT,
    "b2bDeliveryCost" TEXT,
    "customerServicePhone" TEXT,
    "openingHoursMessageKey" TEXT,
    "onlineStore" BOOLEAN,
    "pickingCostForCollectPlusPickupCost" TEXT,
    "b2bPickingCostForCollectPlusPickupCost" TEXT,
    "pickingCostForDeliveryPlusDeliveryCost" TEXT,
    "b2bPickingCostForDeliveryPlusDeliveryCost" TEXT,
    "openingStoreMessageValue" TEXT,
    "b2BClickAndCollect" BOOLEAN,
    "franchiseStore" BOOLEAN,
    "freeDeliveryThresholdFormatted" TEXT,
    "b2bFreeDeliveryThresholdFormatted" TEXT,
    "pickupInStoreCost" TEXT,
    "b2bPickupInStoreCost" TEXT,
    "customerServiceEmail" TEXT,
    "flyerURL" TEXT,
    "activelySelected" BOOLEAN,
    "freePickingCostThresholdForCollectFormatted" TEXT,
    "freePickingCostThresholdForDeliveryFormatted" TEXT,
    "freeB2BPickingCostThresholdForCollectFormatted" TEXT,
    "freeB2BPickingCostThresholdForDeliveryFormatted" TEXT,
    "external" BOOLEAN,
    "name" TEXT,
    "open" BOOLEAN,
    "specialOpeningHours" TEXT,
    "geoPoint_latitude" REAL,
    "geoPoint_longitude" REAL,
    "address_id" TEXT,
    "address_line1" TEXT,
    "address_town" TEXT,
    "address_postalCode" TEXT,
    "address_country_isocode" TEXT,
    "address_country_name" TEXT,
    "address_shippingAddress" BOOLEAN,
    "address_billingAddress" BOOLEAN,
    "address_defaultAddress" BOOLEAN,
    "address_visibleInAddressBook" BOOLEAN,
    "address_formattedAddress" TEXT,
    "address_longitude" REAL,
    "address_latitude" REAL,
    "address_phone" TEXT,
    "address_email" TEXT
);

CREATE TABLE IF NOT EXISTS ica_stores (
    "id" SERIAL PRIMARY KEY,
    "scrapped_date" DATE,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "storeName" TEXT,
    "profile" TEXT,
    "phoneNumber" TEXT,
    "services" TEXT[],
    "emailAddress" TEXT,
    "storeId" TEXT,
    "accountNumber" TEXT,
    "onlinePlatform" TEXT,
    "onlineUrl" TEXT,
    "address_street" TEXT,
    "address_city" TEXT,
    "address_postalCode" TEXT,
    "address_county" TEXT,
    "address_region" TEXT,
    "address_municipality" TEXT,
    "address_urbanArea" TEXT,
    "address_coordinateX" TEXT,
    "address_coordinateY" TEXT,
    "mdsaFilters_informations" TEXT[],
    "mdsaFilters_profile" TEXT,
    "mdsaFilters_services" TEXT[],
    "mdsaFilters_urbanArea" TEXT,
    "mdsaFilters_district" TEXT
);